### ISSUE TITLE
My app is not working after integrate rewardads

### ISSUE THREAD

**Issue by rajsingha** [googlesamples/android-ads#12]
2019-04-24 11:53:55.681 19092-19092/? E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.gmoney.app, PID: 19092
    java.lang.NoClassDefFoundError: Failed resolution of: Lcom/google/android/gms/internal/zziw;
        at com.google.android.gms.internal.zzjo.<init>(Unknown Source:12)
        at com.google.android.gms.internal.zzjo.<clinit>(Unknown Source:9)
        at com.google.android.gms.internal.zzjo.zzhv(Unknown Source:0)
        at com.google.android.gms.internal.zzll.zza(Unknown Source:11)
        at com.google.android.gms.ads.MobileAds.initialize(Unknown Source:12)
        at com.google.android.gms.ads.MobileAds.initialize(Unknown Source:1)
        at com.gmoney.app.HomeFragment.loadAd(HomeFragment.java:100)
        at com.gmoney.app.HomeFragment.onViewCreated(HomeFragment.java:93)
        at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1471)
        at android.support.v4.app.FragmentManagerImpl.moveFragmentToExpectedState(FragmentManager.java:1784)
        at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1852)
        at android.support.v4.app.BackStackRecord.executeOps(BackStackRecord.java:802)
        at android.support.v4.app.FragmentManagerImpl.executeOps(FragmentManager.java:2625)
        at android.support.v4.app.FragmentManagerImpl.executeOpsTogether(FragmentManager.java:2411)
        at android.support.v4.app.FragmentManagerImpl.removeRedundantOperationsAndExecute(FragmentManager.java:2366)
        at android.support.v4.app.FragmentManagerImpl.execPendingActions(FragmentManager.java:2273)
        at android.support.v4.app.FragmentManagerImpl.dispatchStateChange(FragmentManager.java:3273)
        at android.support.v4.app.FragmentManagerImpl.dispatchActivityCreated(FragmentManager.java:3229)
        at android.support.v4.app.FragmentController.dispatchActivityCreated(FragmentController.java:201)
        at android.support.v4.app.FragmentActivity.onStart(FragmentActivity.java:620)
        at android.support.v7.app.AppCompatActivity.onStart(AppCompatActivity.java:178)
        at android.app.Instrumentation.callActivityOnStart(Instrumentation.java:1335)
        at android.app.Activity.performStart(Activity.java:7094)
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2777)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2892)
        at android.app.ActivityThread.-wrap11(Unknown Source:0)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1613)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loop(Looper.java:173)
        at android.app.ActivityThread.main(ActivityThread.java:6634)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:547)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:822)
     Caused by: java.lang.ClassNotFoundException: com.google.android.gms.internal.zziw
        at java.lang.VMClassLoader.findLoadedClass(Native Method)
        at java.lang.ClassLoader.findLoadedClass(ClassLoader.java:738)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:363)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
        at com.google.android.gms.internal.zzjo.<init>(Unknown Source:12) 
        at com.google.android.gms.internal.zzjo.<clinit>(Unknown Source:9) 
        at com.google.android.gms.internal.zzjo.zzhv(Unknown Source:0) 
        at com.google.android.gms.internal.zzll.zza(Unknown Source:11) 
        at com.google.android.gms.ads.MobileAds.initialize(Unknown Source:12) 
        at com.google.android.gms.ads.MobileAds.initialize(Unknown Source:1) 
        at com.gmoney.app.HomeFragment.loadAd(HomeFragment.java:100) 
        at com.gmoney.app.HomeFragment.onViewCreated(HomeFragment.java:93) 
        at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1471) 
        at android.support.v4.app.FragmentManagerImpl.moveFragmentToExpectedState(FragmentManager.java:1784) 
        at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1852) 
        at android.support.v4.app.BackStackRecord.executeOps(BackStackRecord.java:802) 
        at android.support.v4.app.FragmentManagerImpl.executeOps(FragmentManager.java:2625) 
        at android.support.v4.app.FragmentManagerImpl.executeOpsTogether(FragmentManager.java:2411) 
        at android.support.v4.app.FragmentManagerImpl.removeRedundantOperationsAndExecute(FragmentManager.java:2366) 
        at android.support.v4.app.FragmentManagerImpl.execPendingActions(FragmentManager.java:2273) 
        at android.support.v4.app.FragmentManagerImpl.dispatchStateChange(FragmentManager.java:3273) 
        at android.support.v4.app.FragmentManagerImpl.dispatchActivityCreated(FragmentManager.java:3229) 
        at android.support.v4.app.FragmentController.dispatchActivityCreated(FragmentController.java:201) 
        at android.support.v4.app.FragmentActivity.onStart(FragmentActivity.java:620) 
        at android.support.v7.app.AppCompatActivity.onStart(AppCompatActivity.java:178) 
        at android.app.Instrumentation.callActivityOnStart(Instrumentation.java:1335) 
        at android.app.Activity.performStart(Activity.java:7094) 
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2777) 
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2892) 
        at android.app.ActivityThread.-wrap11(Unknown Source:0) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1613) 
        at android.os.Handler.dispatchMessage(Handler.java:106) 
        at android.os.Looper.loop(Looper.java:173) 
        at android.app.ActivityThread.main(ActivityThread.java:6634) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:547) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:822) 
     Caused by: java.lang.NoClassDefFoundError: Failed resolution of: Lcom/google/android/gms/dynamic/zzp;
        at com.google.android.gms.internal.zzjo.<init>(Unknown Source:12) 
        at com.google.android.gms.internal.zzjo.<clinit>(Unknown Source:9) 
        at com.google.android.gms.internal.zzjo.zzhv(Unknown Source:0) 
        at com.google.android.gms.internal.zzll.zza(Unknown Source:11) 
        at com.google.android.gms.ads.MobileAds.initialize(Unknown Source:12) 
        at com.google.android.gms.ads.MobileAds.initialize(Unknown Source:1) 
        at com.gmoney.app.HomeFragment.loadAd(HomeFragment.java:100) 
        at com.gmoney.app.HomeFragment.onViewCreated(HomeFragment.java:93) 
        at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1471) 
        at android.support.v4.app.FragmentManagerImpl.moveFragmentToExpectedState(FragmentManager.java:1784) 
        at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1852) 
        at android.support.v4.app.BackStackRecord.executeOps(BackStackRecord.java:802) 
        at android.support.v4.app.FragmentManagerImpl.executeOps(FragmentManager.java:2625) 
        at android.support.v4.app.FragmentManagerImpl.executeOpsTogether(FragmentManager.java:2411) 
        at android.support.v4.app.FragmentManagerImpl.removeRedundantOperationsAndExecute(FragmentManager.java:2366) 
        at android.support.v4.app.FragmentManagerImpl.execPendingActions(FragmentManager.java:2273) 
        at android.support.v4.app.FragmentManagerImpl.dispatchStateChange(FragmentManager.java:3273) 
        at android.support.v4.app.FragmentManagerImpl.dispatchActivityCreated(FragmentManager.java:3229) 
        at android.support.v4.app.FragmentController.dispatchActivityCreated(FragmentController.java:201) 
        at android.support.v4.app.FragmentActivity.onStart(FragmentActivity.java:620) 
        at android.support.v7.app.AppCompatActivity.onStart(AppCompatActivity.java:178) 
        at android.app.Instrumentation.callActivityOnStart(Instrumentation.java:1335) 
        at android.app.Activity.performStart(Activity.java:7094) 
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2777) 
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2892) 
        at android.app.ActivityThread.-wrap11(Unknown Source:0) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1613) 
        at android.os.Handler.dispatchMessage(Handler.java:106) 
        at android.os.Looper.loop(Looper.java:173) 
        at android.app.ActivityThread.main(ActivityThread.java:6634) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:547) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:822) 
     Caused by: java.lang.ClassNotFoundException: Didn't find class "com.google.android.gms.dynamic.zzp" on path: DexPathList[[zip file "/data/app/com.gmoney.app-QOex7_FTHD9_g1dnh7vgig==/base.apk"],nativeLibraryDirectories=[/data/app/com.gmoney.app-QOex7_FTHD9_g1dnh7vgig==/lib/arm, /system/lib, /vendor/lib]]
        at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:125)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:379)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
        at com.google.android.gms.internal.zzjo.<init>(Unknown Source:12) 
        at com.google.android.gms.internal.zzjo.<clinit>(Unknown Source:9) 
        at com.google.android.gms.internal.zzjo.zzhv(Unknown Source:0) 
        at com.google.android.gms.internal.zzll.zza(Unknown Source:11) 
        at com.google.android.gms.ads.MobileAds.initialize(Unknown Source:12) 
        at com.google.android.gms.ads.MobileAds.initialize(Unknown Source:1) 
        at com.gmoney.app.HomeFragment.loadAd(HomeFragment.java:100) 
        at com.gmoney.app.HomeFragment.onViewCreated(HomeFragment.java:93) 
        at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1471) 
        at android.support.v4.app.FragmentManagerImpl.moveFragmentToExpectedState(FragmentManager.java:1784) 
        at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1852) 
        at android.support.v4.app.BackStackRecord.executeOps(BackStackRecord.java:802) 
        at android.support.v4.app.FragmentManagerImpl.executeOps(FragmentManager.java:2625) 
        at android.support.v4.app.FragmentManagerImpl.executeOpsTogether(FragmentManager.java:2411) 
        at android.support.v4.app.FragmentManagerImpl.removeRedundantOperationsAndExecute(FragmentManager.java:2366) 
        at android.support.v4.app.FragmentManagerImpl.execPendingActions(FragmentManager.java:2273) 
        at android.support.v4.app.FragmentManagerImpl.dispatchStateChange(FragmentManager.java:3273) 
        at android.support.v4.app.FragmentManagerImpl.dispatchActivityCreated(FragmentManager.java:3229) 
        at android.support.v4.app.FragmentController.dispatchActivityCreated(FragmentController.java:201) 
        at android.support.v4.app.FragmentActivity.onStart(FragmentActivity.java:620) 
        at android.support.v7.app.AppCompatActivity.onStart(AppCompatActivity.java:178) 
        at android.app.Instrumentation.callActivityOnStart(Instrumentation.java:1335) 
        at android.app.Activity.performStart(Activity.java:7094) 
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2777) 
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2892) 
        at android.app.ActivityThread.-wrap11(Unknown Source:0) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1613) 
        at android.os.Handler.dispatchMessage(Handler.java:106) 
        at android.os.Looper.loop(Looper.java:173) 
        at android.app.ActivityThread.main(ActivityThread.java:6634) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:547) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:822) 

package com.gmoney.app;

import android.content.Context;
import android.content.Intent;
import android.os.Bundle;
import android.support.annotation.NonNull;
import android.support.annotation.Nullable;
import android.support.v4.app.Fragment;
import android.util.Log;
import android.view.LayoutInflater;
import android.view.View;
import android.view.ViewGroup;
import android.widget.Button;
import android.widget.EditText;
import android.widget.TextView;
import android.widget.Toast;

import com.google.android.gms.ads.AdRequest;
import com.google.android.gms.ads.MobileAds;
import com.google.android.gms.ads.reward.RewardItem;
import com.google.android.gms.ads.reward.RewardedVideoAd;
import com.google.android.gms.ads.reward.RewardedVideoAdListener;
import com.google.android.gms.tasks.OnCompleteListener;
import com.google.android.gms.tasks.Task;
import com.google.firebase.auth.FirebaseAuth;
import com.google.firebase.auth.FirebaseUser;
import com.google.firebase.database.DatabaseReference;
import com.google.firebase.database.FirebaseDatabase;

import java.util.HashMap;
import java.util.Objects;

public class HomeFragment extends Fragment implements RewardedVideoAdListener {
    private static final String TAG = HomeFragment.class.getSimpleName();
    private Context context;
    String c;
    int b = 0;
    Button mButton;

   private RewardedVideoAd mAd;
    public HomeFragment() {

    }

    @Nullable
    @Override
    public View onCreateView(@NonNull LayoutInflater inflater, @Nullable ViewGroup container, @Nullable Bundle savedInstanceState) {
        return inflater.inflate(R.layout.fragment_home, container, false);

    }

    @Override
    public void onViewCreated(@NonNull View view, @Nullable Bundle savedInstanceState) {
        super.onViewCreated(view, savedInstanceState);

        final DatabaseReference databaseReference = FirebaseDatabase.getInstance().getReference();
        final FirebaseAuth firebaseAuth = FirebaseAuth.getInstance();
        final String UID = firebaseAuth.getCurrentUser().getUid();

        final EditText editText = view.findViewById(R.id.edt_points);

        view.findViewById(R.id.btn_one_Point).setOnClickListener(new View.OnClickListener() {
            @Override
            public void onClick(View v) {

                String edPOin = editText.getText().toString();
                c = edPOin;

                b = Integer.parseInt(c);

                HashMap<String, Object> hashMap = new HashMap<>();

                hashMap.put("userPoints", b);
                databaseReference.child("Users").child(UID).updateChildren(hashMap).addOnCompleteListener(new OnCompleteListener<Void>() {
                    @Override
                    public void onComplete(@NonNull Task<Void> task) {
                        if (task.isSuccessful()) {
                            Log.d(TAG, "Success");
                        }
                    }
                });

            }
        });

        loadAd();

    }

    private void loadAd() {

        MobileAds.initialize(getActivity(), getString(R.string.admob_app_id));

        mAd = MobileAds.getRewardedVideoAdInstance(getActivity());
        mAd.setRewardedVideoAdListener(this);

        mAd.loadAd(getString(R.string.ad_unit_id),new AdRequest.Builder().build());

        mButton = (Button) getActivity().findViewById(R.id.btn_ads_show);
        mButton.setOnClickListener(new View.OnClickListener() {
            @Override
            public void onClick(View v) {
                mButton.setEnabled(false);
                if (mAd.isLoaded()){
                    mAd.show();
                }

            }
        });
    }

    @Override
    public void onAttach(Context context) {
        super.onAttach(context);
        if (context == null){
            this.context = context;
        }
    }

    @Override
    public void onDestroy() {
        super.onDestroy();
        if (context != null){
            this.context = null;
        }
    }

    @Override
    public void onRewardedVideoAdLoaded() {
        mButton.setEnabled(true);

    }

    @Override
    public void onRewardedVideoAdOpened() {
        Log.d(TAG, "Success");

    }

    @Override
    public void onRewardedVideoStarted() {
        Log.d(TAG, "Success");

    }

    @Override
    public void onRewardedVideoAdClosed() {
        Log.d(TAG, "Success");

    }

    @Override
    public void onRewarded(RewardItem rewardItem) {
        Log.d(TAG, "Success");

    }

    @Override
    public void onRewardedVideoAdLeftApplication() {
        Log.d(TAG, "Success");

    }

    @Override
    public void onRewardedVideoAdFailedToLoad(int i) {
        Log.d(TAG, "Success");

    }
}

**Comment by stowy** [comment]
Hi, thanks for your query.

For support debugging your apps, can we request that you make a request on our [support forum](https://groups.google.com/forum/#!categories/google-admob-ads-sdk/android) at https://groups.google.com/forum/#!categories/google-admob-ads-sdk/android - they will be able to help debug your issue with you efficiently.

Generally these issues are specifically for issues with the sample apps only, as more in depth support for your specific issues is handled by our support team on the forum.

When posting to the forum, please also provide specific details including any errors being seen and code showing how to reproduce the problem.

If you have a specific issue with a sample app, please provide details including which sample app and specific steps to reproduce the issue.
